Appium2
burtonemily/appium pull request #3
Opened 2023-01-16 02:25 UTC by burtonemily

2023-02-15 23:00 UTC, Bilb commented on appium_next.d copy.js
> +"use strict";
this file can be deleted completely

2023-02-16 00:57 UTC, Bilb requested changes

2023-02-16 00:57 UTC, Bilb commented on run/test/specs/disappearing_messages.spec.ts
> +  console.warn("FIXME audric");
to remove

2023-02-16 00:57 UTC, Bilb commented on run/test/specs/create_user_manual.spec.ts
> +  console.warn("FIXME audric");
to remove

2023-02-16 00:57 UTC, Bilb commented on run/test/specs/create_user_manual.spec.ts
> +  // await device2.setImplicitWaitTimeout(50000);
to remove

2023-02-16 02:23 UTC, burtonemily commented on run/test/specs/utils/open_app.ts
> +  // console.warn('installAppToDeviceName ', driver);
Remove lines 106-108?

2023-02-16 02:25 UTC, burtonemily commented on run/test/specs/utils/check_colour.ts
> +  console.warn("base64", base64);
just the console.warn...?

2023-05-04 06:34 UTC, burtonemily commented on run/test/specs/utils/do_function_if_element_exists.ts
> +    await device.findElement(strategy, selector);
Deleted this function, it wasn't doing anything

2023-05-04 06:35 UTC, burtonemily commented on run/test/specs/utils/do_function_if_element_exists.ts
> +  }
Deleted function

2023-08-17 07:02 UTC, Bilb approved these changes

2023-08-17 07:02 UTC, Bilb commented on run/types/sessionIt.ts
> +// }
to be removed

2023-08-17 07:02 UTC, Bilb commented on 21:00:00
same for this file

2023-08-17 07:04 UTC, merged